[package]
name = "simple-space"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
fastrand = { workspace = true }
bevy_simple_text_input = { workspace = true }
avian2d = { workspace = true }
